/**
 * Single source of truth for the site's public identity.
 *
 * The canonical host is the apex domain - www.nexiorastudio.com redirects here,
 * so every canonical, sitemap entry and schema URL must use this value.
 */
export const SITE_URL = 'https://nexiorastudio.com'

export const SITE_NAME = 'Nexiora Studio'

export const SITE_DESCRIPTION =
  'Nexiora Studio is a UK web design and development agency building bespoke, high-converting websites, custom software and AI-powered systems for growing businesses.'

/**
 * The Open Graph image is generated by `app/opengraph-image.tsx`, which Next
 * serves at this path and injects into og:image / twitter:image automatically.
 * Referenced here only so structured data can point at the same asset.
 */
export const DEFAULT_OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'Nexiora Studio - bespoke web design, development and custom software',
}

/** Name, address and phone. Kept here so the visible details and the
 *  LocalBusiness schema can never drift apart. */
export const NAP = {
  legalName: 'Nexiora Studio',
  email: 'echlas@nexiorastudio.com',
  phone: '+44 7835 385 699',
  phoneHref: 'tel:+447835385699',
  whatsapp: 'https://wa.me/447835385699',
  locality: 'London',
  region: 'Greater London',
  country: 'GB',
  countryName: 'United Kingdom',
  geo: { lat: 51.4893, lng: -0.0882 },
  mapsUrl: 'https://maps.app.goo.gl/qqJCMBc42c6YjcM37',
  reviewUrl: 'https://g.page/r/CYIj1G3GZSO-EAI/review',
  areaServed: ['London', 'United Kingdom'],
} as const

export const CALENDLY_URL =
  'https://calendly.com/echlas-nexioratalent/website-consultation'

/** Resolve a site-relative path to an absolute URL. */
export function absoluteUrl(path = '/') {
  return new URL(path, SITE_URL).toString()
}

/** Public social profiles. Rendered in the footer and mirrored into the
 *  `sameAs` of the Organization / LocalBusiness schema. */
export const SOCIAL_LINKS = [
  {
    label: 'Instagram',
    href: 'https://www.instagram.com/nexiorastudio/',
    brand: '#E1306C',
    gradient:
      'linear-gradient(45deg, #F58529 0%, #DD2A7B 45%, #8134AF 75%, #515BD4 100%)',
  },
  {
    label: 'YouTube',
    href: 'https://www.youtube.com/@NexioraStudio',
    brand: '#FF0033',
    gradient: 'linear-gradient(45deg, #FF0033 0%, #FF4E45 100%)',
  },
  {
    label: 'TikTok',
    href: 'https://www.tiktok.com/@nexroast',
    brand: '#25F4EE',
    gradient: 'linear-gradient(45deg, #25F4EE 0%, #FE2C55 100%)',
  },
] as const
